# Generated by Django 3.1.2 on 2020-10-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photos',
            new_name='Image',
        ),
    ]
